/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <Platform_Types.h>


#define GPIOA_BASE 0x40010800
#define GPIOA_CRH *(vuint32_t*)(GPIOA_BASE + 0x04)
#define GPIOA_ODR *(vuint32_t*)(GPIOA_BASE + 0x0C)
#define GPIOA_CRL *(vuint32_t*)(GPIOA_BASE + 0x00)
#define GPIOA_IDR *(vuint32_t*)(GPIOA_BASE + 0x08)


#define GPIOB_BASE 0x40010C00
#define GPIOB_CRH *(vuint32_t*)(GPIOB_BASE + 0x04)
#define GPIOB_ODR *(vuint32_t*)(GPIOB_BASE + 0x0C)
#define GPIOB_CRL *(vuint32_t*)(GPIOB_BASE + 0x00)
#define GPIOB_IDR *(vuint32_t*)(GPIOB_BASE + 0x08)

#define RCC_BASE 0x40021000
#define RCC_APB2ENR *(vuint32_t*)(RCC_BASE + 0x18)
#define RCC_CFGR *(vuint32_t*)(RCC_BASE + 0x04)
#define RCC_IOPAEN (1<<2)
#define RCC_IOPBEN (1<<3)

void clock_init()
{
	RCC_APB2ENR |= RCC_IOPAEN;
	RCC_APB2ENR |= RCC_IOPBEN;

}

void GPIO_init(){

	// Reset the register of GPIOA
	GPIOA_CRL = 0;
	GPIOA_CRH = 0;
	GPIOA_ODR = 0;

	// Configure Input Pin: PA1 & PA13 as Floating input High Z
	GPIOA_CRL |= (1<<6);
	GPIOA_CRH &= ~(0b11<<20);
	GPIOA_CRH |= (0b01<<22);

	// Reset the register of GPIOA
	GPIOB_CRL = 0x0;
	GPIOB_CRH = 0x0;
	GPIOB_ODR = 0x0;

	// Output Pins PB1 & PB13 push-pull mode
	GPIOB_CRL &= ~(0b11<<6); // PB1
	GPIOB_CRL |= (0b01<<4); // PB1

	GPIOB_CRH |= (0b01<<20); // PB13
	GPIOB_CRH &= ~(0b11<<22); // PB13
}

void wait_ms(int time)
{
	vuint32_t i,j;
	for(i=0;i<time;i++)
		for(j=0;j<255;j++);
}
int main(void)
{	// Init clock & GPIOs
	clock_init();
	GPIO_init();
	while (1)
	{
		// PA1 -- PUR
		if(((GPIOA_IDR & (1<<1)) >>1)==0) // button single pressed
		{
			GPIOB_ODR ^= 1<<1;
			while((((GPIOA_IDR & (1<<1)) >>1)==0));
		}
		// PA13 -- PUR
		if(((GPIOA_IDR & (1<<13)) >>13)==1) // button pressed - Multi PRess
		{
			GPIOB_ODR ^= 1<<13;
		}
		wait_ms(1);
	}


}


