/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "STM32F103X6.h"
#include "STM32_GPIO_Driver.h"
#include "lcd.h"
#include "keypad.h"

void Clock_Init()
{
	//enable clock for GPIOA
	RCC_GPIOA_CLK_EN();
	//enable clock for GPIOB
	RCC_GPIOB_CLK_EN();
}


void _delay_ms(unsigned long time){
	unsigned long i,j;
	for(i=0 ;i<time;i++){
		for(j=0;j<255;j++);
	}
}

unsigned char pressed_key;

int main(void)
{
	// init clocks & GPIOs
	Clock_Init();
	LCD_INIT();

	// Start main algo
	// LCD Testing...
	unsigned char LCD_number[] = {'0','1','2','3','4','5','6','7','8','9'};
	LCD_WRITE_STRING("Mohamed welcomes you :) !");
	_delay_ms(500);
	LCD_clear_screen();
	// All char display test
	for(int i =0 ; i<11 ; i++)
	{
		LCD_WRITE_CHAR(LCD_number[i]);
		_delay_ms(100);
	}
	LCD_clear_screen();

	// KEYPAD Testing...
	Keypad_Init();
	LCD_WRITE_STRING("Keypad is now ready");
	_delay_ms(200);
	LCD_clear_screen();
	LCD_WRITE_STRING("Press any key...");
	_delay_ms(100);
	LCD_clear_screen();

	while(1)
	{
		pressed_key = get_pressed_key();
		switch(pressed_key){
		case 'N':
			break;
		case '?':
			LCD_clear_screen();
			break;
		default:
			LCD_WRITE_CHAR(pressed_key);
			break;
		}
	}
}
