/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "STM32F103X6.h"
#include "STM32_GPIO_Driver.h"

void Clock_Init()
{
	//enable clock for GPIOA
	RCC_GPIOA_CLK_EN();
	//enable clock for GPIOB
	RCC_GPIOB_CLK_EN();
}


void GPIO_init()
{
	GPIO_Config_t pin_config;

	//PA1 Input Highz Floating
	pin_config.GPIO_PinNumber = GPIO_PIN_1;
	pin_config.GPIO_PinMode = GPIO_MODE_INPUT_FLO;
	GPIO_Init(GPIOA, &pin_config);

	//PA13 Input Highz Floating
	pin_config.GPIO_PinNumber = GPIO_PIN_13;
	pin_config.GPIO_PinMode = GPIO_MODE_INPUT_FLO;
	GPIO_Init(GPIOA, &pin_config);

	//PB1 Output push pull
	pin_config.GPIO_PinNumber = GPIO_PIN_1;
	pin_config.GPIO_PinMode = GPIO_MODE_OUTPUT_PP;
	pin_config.GPIO_PinSpeed = GPIO_SPEED_10MHz;
	GPIO_Init(GPIOB, &pin_config);

	//PB1 Output push pull
	pin_config.GPIO_PinNumber = GPIO_PIN_13;
	pin_config.GPIO_PinMode = GPIO_MODE_OUTPUT_PP;
	pin_config.GPIO_PinSpeed = GPIO_SPEED_10MHz;
	GPIO_Init(GPIOB, &pin_config);
}

void delay(int x){

	unsigned int i,j;
	for (i=0; i<x;i++)
	{
		for(j=0;j<255;j++);
	}
}

int main(void)
{
	// init clocks & GPIOs
	Clock_Init();
	GPIO_init();

	// Start main algo
	while(1)
	{
		if(GPIO_READ_Pin(GPIOA, GPIO_PIN_1) == 0)// pressed
		{
			GPIO_TOGGLE_Pin(GPIOB,GPIO_PIN_1);
			while(GPIO_READ_Pin(GPIOA, GPIO_PIN_1) == 0); // single pressing
		}
		if(GPIO_READ_Pin(GPIOA, GPIO_PIN_13) == 1) // Multi pressing
			GPIO_TOGGLE_Pin(GPIOB,GPIO_PIN_13);
		delay(1);
	}
}
