/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <Platform_Types.h>


#define GPIOA_BASE 0x40010800
#define GPIOA_CRH *(vuint32_t*)(GPIOA_BASE + 0x04)
#define GPIOA_ODR *(vuint32_t*)(GPIOA_BASE + 0x0C)
#define GPIOA_CRL *(vuint32_t*)(GPIOA_BASE + 0x00)


#define RCC_BASE 0x40021000
#define RCC_APB2ENR *(vuint32_t*)(RCC_BASE + 0x18)
#define RCC_CFGR *(vuint32_t*)(RCC_BASE + 0x04)
#define RCC_IOPAEN (1<<2)
#define RCC_AFIOEN (1<<0)


// Interrupts:
#define EXTI_BASE 0x40010400
#define EXTI_IMR *(vuint32_t*)(EXTI_BASE + 0x00)
#define EXTI_RTSR *(vuint32_t*)(EXTI_BASE + 0x08)
#define EXTI_FTSR *(vuint32_t*)(EXTI_BASE + 0x0C)
#define EXTI_PR *(vuint32_t*)(EXTI_BASE + 0x14)
#define NIVC_ISR0 *(vuint32_t*)(0xE000E100)

#define AFIO_BASE 0x40010000
#define AFIO_EXTICR1 *(vuint32_t*)(GPIOA_BASE + 0x08)



void clock_init()
{
	RCC_APB2ENR |= RCC_IOPAEN;
	RCC_APB2ENR |= RCC_AFIOEN;
	RCC_CFGR |= (0b100 << 8);
	RCC_CFGR |= (0b101 << 11);
}

void GPIO_init(){

	GPIOA_CRH &= 0xFF0FFFFF;
	GPIOA_CRH |= 0x00200000;
	GPIOA_CRL |= (1<<2);
}

int main(void)
{	// Lab Enable Interrupt for EXTI0

	clock_init();
	GPIO_init();
	// Select PortA for EXTI0
	AFIO_EXTICR1 =0x0;

	NIVC_ISR0 |= (1<<6);
	// Enable (Unmask) the EXTI Line 0 that means set the IMR bit_0 to 1
	EXTI_IMR  |= (1<<0) ;
	EXTI_RTSR |= (1<<0) ;

	while (1);

}

void EXTI0_IRQHandler()
{
	// Toggle LED
	GPIOA_ODR ^= (1<<13);
	// Clear the EXTI0 Pending Request
	EXTI_PR |= (1<<0);
}
