/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "STM32F103X6.h"
#include "STM32_GPIO_Driver.h"
#include "STM32_EXTI_Driver.h"
#include "lcd.h"
#include "keypad.h"

void EXTI9_callback(void);
uint32_t IRQ_FLAG =0;
void Clock_Init()
{
	//enable clock for GPIOA
	RCC_GPIOA_CLK_EN();
	//enable clock for GPIOB
	RCC_GPIOB_CLK_EN();
	//open clock of AFIO
	RCC_AFIO_CLK_EN();
}


void _delay_ms(unsigned long time){
	unsigned long i,j;
	for(i=0 ;i<time;i++){
		for(j=0;j<255;j++);
	}
}


int main(void)
{
	// init clocks & GPIOs
	Clock_Init();
	LCD_INIT();
	IRQ_FLAG =1;

	// Start main algo
	EXTI_PINCONFIG_t EXTI_CFG;
	EXTI_CFG.EXTI_PIN = EXTI9PB9;
	EXTI_CFG.Trigger = EXTI_Trigger_RISING;
	EXTI_CFG.IRQ_EN = IRQ_Enable;
	EXTI_CFG.IRQ_CallBack = EXTI9_callback;
	EXTI_Init(&EXTI_CFG);

	/* Loop forever */
	while(1)
	{
		if(IRQ_FLAG)
		{
			LCD_clear_screen();
			_delay_ms(100);
			IRQ_FLAG = 0;
		}


	}
}

void EXTI9_callback(void)
{
	LCD_WRITE_STRING("IRQ EXTI9 is happened _|-");
	IRQ_FLAG = 1;
	_delay_ms(400);
}

