/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <Platform_Types.h>


#define GPIOA_BASE 0x40010800
#define GPIOA_CRH *(vuint32_t*)(GPIOA_BASE + 0x04)
#define GPIOA_ODR *(vuint32_t*)(GPIOA_BASE + 0x0C)

#define RCC_BASE 0x40021000
#define RCC_APB2ENR *(vuint32_t*)(RCC_BASE + 0x18)
#define RCC_IOPAEN (1<<2)

int main(void)
{	// Lab 1: Not enabling the Clock for the GPIO Module, it is expected that nothing happens
	//RCC_APB2ENR |= RCC_IOPAEN;
	GPIOA_CRH &= 0xFF0FFFFF;
	GPIOA_CRH |= 0x00200000;
	while (1)
	{
		GPIOA_ODR |= (1<<13);
		for(int i=0;i<100;i++);
		GPIOA_ODR &= ~(1<<13);
		for(int i=0;i<100;i++);
	}

}

