/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stdint.h>
#include <Platform_Types.h>

#define SYSCTL_RCGC2_R     (*((vuint32_t*)0x400FE108))
#define GPIO_PORTF_DATA_R  (*((vuint32_t*)0x400253FC))
#define GPIO_PORTF_DIR_R   (*((vuint32_t*)0x40025400))
#define GPIO_PORTF_DEN_R   (*((vuint32_t*)0x4002551C))

int main (void)
{
	vuint32_t delay_count; 
	SYSCTL_RCGC2_R = 0x00000020; 
	for (delay_count=0;delay_count<2000; delay_count++);
	GPIO_PORTF_DEN_R |= 1<<3;
	GPIO_PORTF_DIR_R |= 1<<3;

	while (1)
	{
		GPIO_PORTF_DATA_R |= 1<<3;
		for (delay_count=0;delay_count<2000; delay_count++);
		GPIO_PORTF_DATA_R &= ~(1<<3);
		for (delay_count=0;delay_count<2000; delay_count++);
	}
	

	return 0;
}