/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stdint.h>
#include <Platform_Types.h>


#define RCC_BASE 0x40021000
#define GPIO_BASE 0x40010800

#define RCC_APB2ENR *((vuint32_t*)(RCC_BASE + 0x18))
#define GPIOA_CRH *((vuint32_t*)(GPIO_BASE + 0x04))
#define GPIOA_ODR *((vuint32_t*)(GPIO_BASE + 0x0C))

#define RCC_IOPAEN (1<<2)
#define GPIO13 (1UL<<13)

typedef union {
	vuint32_t all_fields;
	struct {
		vuint32_t reserved:13;
		vuint32_t P_13:1;
	}Pin;
}R_ODR_t;

volatile R_ODR_t* R_ODR = (volatile R_ODR_t*)(GPIO_BASE + 0x0C);


int main(void)
{
	RCC_APB2ENR |= RCC_IOPAEN;
	GPIOA_CRH &= 0xFF0FFFFF;
	GPIOA_CRH |= 0x00200000;
	while(1)
	{
		R_ODR->Pin.P_13 = 1;
		int i=0;
		for(i=0; i<5000;i++); // Delay
		R_ODR->Pin.P_13 = 0;
		for(i=0; i<500;i++); // Delay

	}
	return 0;
}
